name: "suggester / yaml"
description: "Uses reviewdog to suggest yaml format changes."

inputs:
  changed_yaml_files:
    description: “list of changed yaml files.”
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@4
    - run: pip install yamlfixer-opt-nc
    - run: yamlfixer ${{ inputs.changed_yaml_files }}
      shell: bash
      continue-on-error: true
    - uses: reviewdog/action-suggester@v1
      with:
        tool_name: yamlfixer
        filter_mode: 'file'

    - uses: reviewdog/action-yamllint@v1
      with:
        #github_token: ${{ secrets.github_token }}
        yamllint_flags: '${{ inputs.changed_yaml_files }}'
        filter_mode: 'file'
