name: "suggester / yaml"
description: "Uses reviewdog to suggest yaml format changes."

inputs:
  changed_yaml_files:
    description: “list of changed yaml files.”
    required: true

runs:
  using: "composite"
  steps:
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip3 install yamlfixer-opt-nc
      shell: bash
    - run: yamlfixer ${{ inputs.changed_yaml_files }}
      shell: bash
      continue-on-error: true
    - uses: reviewdog/action-suggester@v1
      with:
        tool_name: yamlfixer
        filter_mode: 'file'

    - uses: reviewdog/action-yamllint@v1
      with:
        #github_token: ${{ secrets.github_token }}
        yamllint_flags: '${{ inputs.changed_yaml_files }}'
        filter_mode: 'file'
