name: "suggester / yaml"
description: "Uses reviewdog to suggest yaml format changes."

inputs:
  changed_yaml_files:
    description: “list of changed yaml files.”
    required: true

runs:
  using: "composite"
  steps:
     - uses: actions/checkout@v3
     - uses: reviewdog/action-yamllint@v1
       with:
         reporter: github-pr-review # Change reporter.
         level: error
